#pragma once

#include <builtinFonts/bookerly_12_bold.h>
#include <builtinFonts/bookerly_12_bolditalic.h>
#include <builtinFonts/bookerly_12_italic.h>
#include <builtinFonts/bookerly_12_regular.h>
#include <builtinFonts/bookerly_14_bold.h>
#include <builtinFonts/bookerly_14_bolditalic.h>
#include <builtinFonts/bookerly_14_italic.h>
#include <builtinFonts/bookerly_14_regular.h>
#include <builtinFonts/bookerly_16_bold.h>
#include <builtinFonts/bookerly_16_bolditalic.h>
#include <builtinFonts/bookerly_16_italic.h>
#include <builtinFonts/bookerly_16_regular.h>
#include <builtinFonts/bookerly_18_bold.h>
#include <builtinFonts/bookerly_18_bolditalic.h>
#include <builtinFonts/bookerly_18_italic.h>
#include <builtinFonts/bookerly_18_regular.h>
#include <builtinFonts/notosanstc_8_regular.h>
#include <builtinFonts/notosanstc_12_bold.h>
#include <builtinFonts/notosanstc_12_bolditalic.h>
#include <builtinFonts/notosanstc_12_italic.h>
#include <builtinFonts/notosanstc_12_regular.h>
#include <builtinFonts/notosanstc_14_bold.h>
#include <builtinFonts/notosanstc_14_bolditalic.h>
#include <builtinFonts/notosanstc_14_italic.h>
#include <builtinFonts/notosanstc_14_regular.h>
#include <builtinFonts/notosanstc_16_bold.h>
#include <builtinFonts/notosanstc_16_bolditalic.h>
#include <builtinFonts/notosanstc_16_italic.h>
#include <builtinFonts/notosanstc_16_regular.h>
#include <builtinFonts/notosanstc_18_bold.h>
#include <builtinFonts/notosanstc_18_bolditalic.h>
#include <builtinFonts/notosanstc_18_italic.h>
#include <builtinFonts/notosanstc_18_regular.h>
#include <builtinFonts/notosanstc_10_bold.h>
#include <builtinFonts/notosanstc_10_regular.h>
#include <builtinFonts/notosanstc_12_bold.h>
#include <builtinFonts/notosanstc_12_regular.h>
